#!/bin/bash
echo '##################>/home/dataverse/customHtml/'$1
if [ -f "$1" ]; then
        echo "Arquivo OK "+$1
        curl -X PUT -d '/home/dataverse/customHtml/'$1 http://localhost:8080/api/admin/settings/:HomePageCustomizationFile
        echo " "
else
        echo "ERRO"
fi
